version: "3.8"
services:
  # PHP BACKEND APPLICATION
  notifications-app-backend:
    container_name: notifications-app-backend
    build:
      context: ../app-notifications-ms/
      dockerfile: docker-compose/Dockerfile
      args:
        PHP_OPCACHE_ENABLE: 0
        PHP_OPCACHE_ENABLE_CLI: 0
        PHP_OPCACHE_VALIDATE_TIMESTAMPS: 0
        PHP_OPCACHE_REVALIDATE_FREQ: 0
    image: notifications-app-back
    environment:
      - APP_NAME="Application Notifications Backend"
      - APP_ENV="local"
      - APP_DEBUG="true"
      - APP_KEY="base64:JryWTFZdbNrr3Z51VNx+gbQEPTWV+tMvetwPNI3IFBU="
      - DB_CONNECTION="pgsql"
      - DB_HOST="notifications-db"
      - DB_PORT="5432"
      - DB_DATABASE="notifications"
      - DB_USERNAME="postgres"
      - DB_PASSWORD="postgres"
    working_dir: /var/www
    ports:
      - "7075:8000"
    links:
      - notifications-db
    depends_on:
      - notifications-db
  # FRONT END APPLICATION
  notifications-app-frontend:
    container_name: notifications-app-frontend
    build:
      context: ../app-notifications-frontend/
      dockerfile: docker-compose/Dockerfile
    image: notifications-app-frontend
    environment:
      - APP_NAME="Application Notifications Frontend"
    working_dir: /var/www
    ports:
      - "7074:80"
    links:
      - notifications-app-backend
    depends_on:
      - notifications-app-backend
  # Database Server
  notifications-db:
    container_name: notifications-db
    image: postgres
    restart: always
    ports:
      - "45432:5432"
    environment:
      - POSTGRES_DB=notifications
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres